autores/urls.py
from autores import views
from django.urls import path

app_name = "autores"
urlpatterns = [
    path("list/", views.AutorListView.as_view(), name="list"),
    path("create/", views.AutorCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.AutorUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.AutorDeleteView.as_view(), name="delete"),
    path("detail/<int:pk>/", views.AutorDetailView.as_view(), name="detail"),
]

biblioteca/urls.py
from django.contrib import admin
from django.urls import include, path  # noqa
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("autores/", include("autores.urls", namespace="autores")),
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"), # noqa
]

autores/models.py
from django.db import models


class Autor(models.Model):
    nome = models.CharField(max_length=100)
    biografia = models.TextField()
    data_nascimento = models.DateField()

    def __str__(self):
        return self.nome

autores/forms.py
from autores.models import Autor
from django import forms
from django.utils.translation import gettext_lazy as _


class AutorForms(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ["nome", "biografia", "data_nascimento"]
        widgets = {
            "data_nascimento": forms.DateInput(
                attrs={
                    "placeholder": _("Data de nascimento"),
                    "data-input": "data-input",
                    "type": "date"
                }
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance is not None:
            self.initial['data_nascimento'] = instance.data_nascimento.strftime('%Y-%m-%d') # noqa

autores/views.py
from autores import forms, models
from django.contrib.messages import views
from django.urls import reverse_lazy
from django.views import generic


# Create your views here.
class AutorListView(generic.ListView):
    model = models.Autor
    context_object_name = "autores"
    template_name = "autores/autor_list.html"
    paginate_by = 5


class AutorCreateView(views.SuccessMessageMixin, generic.CreateView):
    model = models.Autor
    form_class = forms.AutorForms
    template_name = "autores/autor_form.html"
    success_url = reverse_lazy("autores:list")
    success_message = "Autor criado com sucesso!"


class AutorUpdateView(views.SuccessMessageMixin, generic.UpdateView):
    model = models.Autor
    form_class = forms.AutorForms
    template_name = "autores/autor_form.html"
    success_url = reverse_lazy("autores:list")
    success_message = "Autor atualizado com sucesso!"


class AutorDeleteView(views.SuccessMessageMixin, generic.DeleteView):
    model = models.Autor
    template_name = "autores/autor_confirm_delete.html"
    success_url = reverse_lazy("autores:list")
    success_message = "Autor excluído com sucesso!"


class AutorDetailView(generic.DetailView):
    model = models.Autor
    context_object_name = "autor"
    template_name = "autores/autor_detail.html"

autores/templates/autores/autor_confirm_delete.html
<form action="{% url delete_url object.pk %}" method="post">
  {% csrf_token %}
  <div class="modal fade"
       id="deleteModal-{{ object.pk }}"
       tabindex="-1"
       aria-labelledby="deleteModalLabel"
       aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="deleteModalLabel">Confirmação de Exclusão</h1>
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"></button>
        </div>
        <div class="modal-body">Deseja excluir o elemento {{ object.name }}?</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-danger">Excluir</button>
        </div>
      </div>
    </div>
  </div>
</form>

autores/templates/autores/autor_detail.html
{% extends "base.html" %}

{% load static %}

{% block page_name %}
  Detalhe do Autor
{% endblock page_name %}

{% block content %}
  <div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Dados do Autor</h3>
    </div>
    <div class="card-body p-0">
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Código:</strong>
        </div>
        <div id="codigo" class="col-md-10 col-sm-12">{{ object.pk }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Nome:</strong>
        </div>
        <div id="name" class="col-md-10 col-sm-12">{{ object.nome }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Nascimento:</strong>
        </div>
        <div id="teacher" class="col-md-10 col-sm-12">{{ object.data_nascimento }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Biografia:</strong>
        </div>
        <div id="shift" class="col-md-10 col-sm-12">{{ object.biografia }}</div>
      </div>
      <div class="row justify-content-between m-3">
        <div class="col-lg-4 col-md-6 col-12 m-3">
          <a type="button"
             class="btn btn-secondary"
             href="{% url 'autores:list' %}"> <i class="fas fa-chevron-left mr-1" aria-hidden="true"></i>Voltar</a>
        </div>
        <div class="col-lg-2 col-md-3 col-12 m-3">
          <a class="btn btn-primary"
             href="{% url 'autores:update' object.pk %}">Editar</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

autores/templates/autores/autor_form.html
{% extends "base.html" %}

{% load i18n %}
{% load bootstrap5 %}

{% block page_name %}
    {% if object.pk %}
        Edição de Autor
    {% else %}
        Cadastro de Autor
    {% endif %}
{% endblock page_name %}

{% block content %}
  {% block alerts %}
    {% include "layouts/alerts.html" %}
  {% endblock alerts %}
  <div class="card card-primary mx-3">
    <div class="card-body p-0 mt-3">
      <form method="post" autocomplete="off">
        {% csrf_token %}
          <div class="col-12 col-sm-6">{% bootstrap_field form.nome %}</div>
          <div class="col-12 col-sm-6">{% bootstrap_field form.data_nascimento %}</div>
          <div class="col-12 col-sm-6">{% bootstrap_field form.biografia %}</div>

        <div class="row justify-content-between m-3">
            <div class="col-lg-4 col-md-6 col-12 m-3">
                <a type="button" class="btn btn-secondary" href="{% url 'autores:list' %}">
                <i class="fas fa-chevron-left mr-1" aria-hidden="true"></i>
                Voltar</a>
            </div>
            <div class="col-lg-2 col-md-3 col-12 m-3">
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
        </div>
        
      </form>
    </div>
  </div>
{% endblock content %}

autores/templates/autores/autor_list.html
{% extends "base.html" %}

{% block page_name %}
  Lista de Autores
{% endblock page_name %}

{% block content %}
<div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Autores Cadastrados</h3>
    </div>
    <div class="card-body p-0" style="overflow-x: auto">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Nascimento</th>
            <th class="text-center">Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>{{ object.pk }}</td>
              <td>{{ object.nome }}</td>
              <td>{{ object.data_nascimento }}</td>
              <td class="text-center">
                <a href="{% url 'autores:detail' object.pk %}"><i class="fas fa-eye" aria-hidden="true"></i></a>
                <a class="mx-1"
                   href="{% url 'autores:update' object.pk %}"
                   type="button"
                   aria-label="editar"
                   title="editar">
                  <i class="fas fa-edit" aria-hidden="true"></i></a>
                <a type="button"
                   data-bs-toggle="modal"
                   data-bs-target="#deleteModal-{{ object.pk }}"
                   aria-label="excluir"
                   title="excluir">
                  <i class="fas fa-trash" aria-hidden="true"></i></a>
                {% include "autores/autor_confirm_delete.html" with delete_url="autores:delete" %}
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="4">
                <p>Não existem séries cadastradas.</p>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if object_list %}
      {% include 'adminlte/lib/_pagination.html' %}
    {% endif %}
  </div>
  <div class="row justify-content-between m-3">
    <div class="col-lg-4 col-md-6 col-12 m-3">
      <a type="button" class="btn btn-secondary" href="{% url 'home' %}">
        <i class="fas fa-chevron-left mr-1" aria-hidden="true"></i>
      Voltar</a>
    </div>
    <div class="col-lg-2 col-md-3 col-12 m-3">
        <a class="btn btn-primary" href="{% url 'autores:create' %}">Cadastrar</a>
    </div>
  </div>
  
{% endblock content %}

templates/adminlte/lib/_main_footer.html
{% extends 'adminlte/lib/_main_footer.html' %}

{% block version %}1.0{% endblock %}
{% block legal %}
  <strong>Copyright &copy; {% now "Y" %}
    {% if not site %}.{% endif %}
    {% if site %}<a href="https://{{ site.domain }}">{{ site.name }}</a>{% endif %}
  </strong> All rights reserved by Raphael Muniz.
{% endblock legal %}

templates/adminlte/lib/_main_header.html
{% extends 'adminlte/lib/_main_header.html' %}

<!-- Header Navbar: style can be found in header.less -->
{% block nav_bar %}
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'home' %}" class="nav-link">Home</a>
    </li>
  </ul>
  {% block nav_bar_center %}
    {{ block.super }}
  {% endblock nav_bar_center %}
  {% block nav_custom_menu %}
    {{ block.super }}
  {% endblock nav_custom_menu %}
  {% block nav_bar_right %}
    {{ block.super }}
  {% endblock nav_bar_right %}
{% endblock nav_bar %}

templates/adminlte/lib/_main_sidebar.html
{% extends 'adminlte/lib/_main_sidebar.html' %}

{% load adminlte_helpers %}

{% block logo_text %}
  <span class="brand-text font-weight-light">Library</span>
{% endblock logo_text %}
{% block user_panel %}
  <!-- Sidebar user panel (optional) -->
  {% if not request.user.is_anonymous %}
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% avatar_url size=90 %}"
             class="img-circle elevation-2"
             alt="User Image" />
      </div>
      <div class="info">
        <a href="{% url 'home' %}" class="d-block">{% firstof request.user.name request.user.username %}</a>
      </div>
    </div>
  {% endif %}
{% endblock user_panel %}
{% block nav_heading %}
  Menu Principal
{% endblock nav_heading %}
{% block nav_links %}
  <li class="nav-item">
    <a href="{% url 'home' %}" class="nav-link">
      <i class="nav-icon fas fa-home" aria-hidden="true"></i>
      <p>Página Inicial</p>
    </a>
  </li>
  <li class="nav-item">
    <a href="{% url 'autores:list' %}" class="nav-link">
      <i class="nav-icon fas fa-users" aria-hidden="true"></i>
      <p>Autores</p>
    </a>
  </li>
  <li class="nav-item">
    <a href="#" class="nav-link">
      <i class="nav-icon fas fa-book" aria-hidden="true"></i>
      <p>Livros</p>
    </a>
  </li>
  <li class="nav-item">
    <a href="#" class="nav-link">
      <i class="nav-icon fas fa-exchange-alt" aria-hidden="true"></i>
      <p>Empréstimos</p>
    </a>
  </li>
{% endblock nav_links %}

templates/adminlte/lib/_pagination.html
<div class="card-footer clearfix">
  <ul class="pagination pagination-sm m-0 justify-content-center">
    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
      <a class="page-link" href="?page=1">&laquo;&laquo;</a>
    </li>
    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
      <a class="page-link"
         href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}">&laquo;</a>
    </li>
    {% for i in page_obj.paginator.page_range %}
      <li class="page-item{% if i == page_obj.number %} active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}
    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
      <a class="page-link"
         href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}">&raquo;</a>
    </li>
    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
      <a class="page-link"
         href="?page={% if page_obj.has_next %}{{ page_obj.paginator.num_pages }}{% endif %}">&raquo;&raquo;</a>
    </li>
  </ul>
</div>

templates/base.html
{% extends "adminlte/base.html" %}

{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        Gerenciamento de Cantina Escolar
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Behold My Awesome Project!" />
    <meta name="author" content="Raphael Muniz" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <!-- Your stuff: Third-party CSS libraries go here -->
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block extra_head %}
      <!-- Bootstrap JS -->
      <script defer
              src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
              integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- This file stores project-specific CSS -->
      <link href="{% static 'css/project.css' %}" rel="stylesheet" />
      <!-- Latest compiled and minified Bootstrap CSS -->
      <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
            integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer" />
      <!-- place project specific Javascript in this file -->
      <script src="https://unpkg.com/htmx.org/dist/htmx.js"></script>
      <script defer src="{% static 'js/project.js' %}"></script>
      <script defer src="{% static 'js/jquery.mask.min.js' %}"></script>
    {% endblock extra_head %}
  </head>
  <body>
    <main class="container">
      {% block page_name %}
      {% endblock page_name %}
      {% block page_actions %}
      {% endblock page_actions %}
      {% block breadcrumbs %}
        <nav class="ml-3"
             style="--bs-breadcrumb-divider: '>'"
             aria-label="breadcrumb">
          <ol class="breadcrumb">
            {% block breadcrumb_items %}
            {% endblock breadcrumb_items %}
          </ol>
        </nav>
      {% endblock breadcrumbs %}
      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </main>
    <!-- /container -->
    {% block modal %}
    {% endblock modal %}
    {% block extra_js %}
      {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
      {% endcomment %}
    {% endblock extra_js %}
  </body>
</html>

templates/layouts/alerts.html
{% if form.errors %}
  <div class="alert alert-warning alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    {% for error in form.non_field_errors %}<p>{{ error }}</p>{% endfor %}
    {% include "_form_field_error.html" %}
  </div>
{% endif %}

templates/layouts/messages.html
{% for message in messages %}
  <div class="br-message {{ message.tags }}" role="alert">
    <div class="icon">
      <i class="fas fa-check-circle fa-lg" aria-hidden="true"></i>
    </div>
    <div class="content">
      <span class="message-body">
        <div class="alert">
          <p>{{ message|safe }}</p>
        </div>
      </span>
    </div>
    <div class="close">
      <button class="br-button circle small" type="button" aria-label="Fechar">
        <i class="fas fa-times" aria-hidden="true"></i>
      </button>
    </div>
  </div>
{% endfor %}

templates/pages/about.html
{% extends "base.html" %}

templates/pages/home.html
{% extends "base.html" %}

{% block title %}
  Página Inicial
{% endblock title %}
{% block content %}
  <h1>Página Inicial</h1>

  
{% endblock content %}